apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-real-ip: 'true'
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: '0.0.0.0/0'
    nginx.ingress.kubernetes.io/forwarded-for-header: 'X-Forwarded-For'
    nginx.ingress.kubernetes.io/proxy-protocol: 'true'  # Required if using PROXY protocol
       # Additional recommended settings for IP preservation
    nginx.ingress.kubernetes.io/proxy-body-size: '10m'
    nginx.ingress.kubernetes.io/proxy-buffering: 'off'
    nginx.ingress.kubernetes.io/connection-proxy-header: 'keep-alive'
    # nginx.ingress.kubernetes.io/rewrite-target: /$1 # This rewrites the path to match the backend service
spec:
  ingressClassName: nginx # Specify the ingress class to use
  rules:
    - host: localhost # Use localhost for local development
      # host: ticketing.dev # Uncomment this line if you want to use a custom domain
      # Note: If using a custom domain, ensure that the domain resolves to your local machine.
      # You can add an entry in /etc/hosts like:
      #
      # # Add host entry to /etc/hosts
      # echo "127.0.0.1 ticketing.dev" | sudo tee -a /etc/hosts
      http:
        paths:
          - path: /api/v1/user/?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: auth-srv
                port:
                  number: 3000
          - path: /api/v1/tickets/?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: tickets-srv
                port:
                  number: 3000
          - path: /api/v1/orders/?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: tickets-srv
                port:
                  number: 3000
          - path: /api/v1/payments/?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: tickets-srv
                port:
                  number: 3000
          - path: /?(.*)
            pathType: ImplementationSpecific # This allows regex paths
            backend:
              service:
                name: client-srv
                port:
                  number: 3000
